name: Update production website
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: "Update wiki"
    steps:
      - name: Clone public pages
        uses: actions/checkout@v3
        with:
          path: "pages"
          clean: true
          token: ${{ secrets.CI }}

      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          repository: "elitegamers-wiki/wiki-prod"
          ref: "main"
          path: "prod"
          clean: true
          token: ${{ secrets.CI }}

      - name: Update production pages
        run: |
          git config --global user.email "github@elitegamers.ro"
          git config --global user.name "elitegamers-wiki"
          
          for file in prod/docs/*.md; do
            if [ "$(basename "$file")" != "index.md" ] && [ ! -f "pages/$(basename "$file")" ]; then
              rm "$file"
            fi
          done

          cp pages/*.md prod/docs/

          cd prod

          git status
          git add .
          git commit -m "ci: updated pages"
          git push || true
